# Generated by Django 2.1.3 on 2018-11-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=264)),
                ('city', models.CharField(max_length=264)),
                ('country', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(max_length=264)),
                ('return_date', models.DateField(max_length=264)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.CharField(max_length=264)),
                ('real_cost', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Vehicle_size'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Vehicle_type'),
        ),
        migrations.AddField(
            model_name='rental_rate',
            name='vehicle_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Vehicle_size'),
        ),
        migrations.AddField(
            model_name='rental_rate',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Vehicle_type'),
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Vehicle'),
        ),
    ]
